package cn.nicolite.huthelper.db.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 5): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 5;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        ConfigureDao.createTable(db, ifNotExists);
        ExamDao.createTable(db, ifNotExists);
        ExpLessonDao.createTable(db, ifNotExists);
        GradeDao.createTable(db, ifNotExists);
        GradeRankDao.createTable(db, ifNotExists);
        GradeSumDao.createTable(db, ifNotExists);
        LessonDao.createTable(db, ifNotExists);
        MenuDao.createTable(db, ifNotExists);
        NoticeDao.createTable(db, ifNotExists);
        SearchHistoryDao.createTable(db, ifNotExists);
        TimeAxisDao.createTable(db, ifNotExists);
        UserDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        ConfigureDao.dropTable(db, ifExists);
        ExamDao.dropTable(db, ifExists);
        ExpLessonDao.dropTable(db, ifExists);
        GradeDao.dropTable(db, ifExists);
        GradeRankDao.dropTable(db, ifExists);
        GradeSumDao.dropTable(db, ifExists);
        LessonDao.dropTable(db, ifExists);
        MenuDao.dropTable(db, ifExists);
        NoticeDao.dropTable(db, ifExists);
        SearchHistoryDao.dropTable(db, ifExists);
        TimeAxisDao.dropTable(db, ifExists);
        UserDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(ConfigureDao.class);
        registerDaoClass(ExamDao.class);
        registerDaoClass(ExpLessonDao.class);
        registerDaoClass(GradeDao.class);
        registerDaoClass(GradeRankDao.class);
        registerDaoClass(GradeSumDao.class);
        registerDaoClass(LessonDao.class);
        registerDaoClass(MenuDao.class);
        registerDaoClass(NoticeDao.class);
        registerDaoClass(SearchHistoryDao.class);
        registerDaoClass(TimeAxisDao.class);
        registerDaoClass(UserDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
