package cn.nicolite.huthelper.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.nicolite.huthelper.model.bean.Configure;
import cn.nicolite.huthelper.model.bean.Exam;
import cn.nicolite.huthelper.model.bean.ExpLesson;
import cn.nicolite.huthelper.model.bean.Grade;
import cn.nicolite.huthelper.model.bean.GradeRank;
import cn.nicolite.huthelper.model.bean.GradeSum;
import cn.nicolite.huthelper.model.bean.Lesson;
import cn.nicolite.huthelper.model.bean.Menu;
import cn.nicolite.huthelper.model.bean.Notice;
import cn.nicolite.huthelper.model.bean.SearchHistory;
import cn.nicolite.huthelper.model.bean.TimeAxis;
import cn.nicolite.huthelper.model.bean.User;

import cn.nicolite.huthelper.db.dao.ConfigureDao;
import cn.nicolite.huthelper.db.dao.ExamDao;
import cn.nicolite.huthelper.db.dao.ExpLessonDao;
import cn.nicolite.huthelper.db.dao.GradeDao;
import cn.nicolite.huthelper.db.dao.GradeRankDao;
import cn.nicolite.huthelper.db.dao.GradeSumDao;
import cn.nicolite.huthelper.db.dao.LessonDao;
import cn.nicolite.huthelper.db.dao.MenuDao;
import cn.nicolite.huthelper.db.dao.NoticeDao;
import cn.nicolite.huthelper.db.dao.SearchHistoryDao;
import cn.nicolite.huthelper.db.dao.TimeAxisDao;
import cn.nicolite.huthelper.db.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig configureDaoConfig;
    private final DaoConfig examDaoConfig;
    private final DaoConfig expLessonDaoConfig;
    private final DaoConfig gradeDaoConfig;
    private final DaoConfig gradeRankDaoConfig;
    private final DaoConfig gradeSumDaoConfig;
    private final DaoConfig lessonDaoConfig;
    private final DaoConfig menuDaoConfig;
    private final DaoConfig noticeDaoConfig;
    private final DaoConfig searchHistoryDaoConfig;
    private final DaoConfig timeAxisDaoConfig;
    private final DaoConfig userDaoConfig;

    private final ConfigureDao configureDao;
    private final ExamDao examDao;
    private final ExpLessonDao expLessonDao;
    private final GradeDao gradeDao;
    private final GradeRankDao gradeRankDao;
    private final GradeSumDao gradeSumDao;
    private final LessonDao lessonDao;
    private final MenuDao menuDao;
    private final NoticeDao noticeDao;
    private final SearchHistoryDao searchHistoryDao;
    private final TimeAxisDao timeAxisDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        configureDaoConfig = daoConfigMap.get(ConfigureDao.class).clone();
        configureDaoConfig.initIdentityScope(type);

        examDaoConfig = daoConfigMap.get(ExamDao.class).clone();
        examDaoConfig.initIdentityScope(type);

        expLessonDaoConfig = daoConfigMap.get(ExpLessonDao.class).clone();
        expLessonDaoConfig.initIdentityScope(type);

        gradeDaoConfig = daoConfigMap.get(GradeDao.class).clone();
        gradeDaoConfig.initIdentityScope(type);

        gradeRankDaoConfig = daoConfigMap.get(GradeRankDao.class).clone();
        gradeRankDaoConfig.initIdentityScope(type);

        gradeSumDaoConfig = daoConfigMap.get(GradeSumDao.class).clone();
        gradeSumDaoConfig.initIdentityScope(type);

        lessonDaoConfig = daoConfigMap.get(LessonDao.class).clone();
        lessonDaoConfig.initIdentityScope(type);

        menuDaoConfig = daoConfigMap.get(MenuDao.class).clone();
        menuDaoConfig.initIdentityScope(type);

        noticeDaoConfig = daoConfigMap.get(NoticeDao.class).clone();
        noticeDaoConfig.initIdentityScope(type);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        timeAxisDaoConfig = daoConfigMap.get(TimeAxisDao.class).clone();
        timeAxisDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        configureDao = new ConfigureDao(configureDaoConfig, this);
        examDao = new ExamDao(examDaoConfig, this);
        expLessonDao = new ExpLessonDao(expLessonDaoConfig, this);
        gradeDao = new GradeDao(gradeDaoConfig, this);
        gradeRankDao = new GradeRankDao(gradeRankDaoConfig, this);
        gradeSumDao = new GradeSumDao(gradeSumDaoConfig, this);
        lessonDao = new LessonDao(lessonDaoConfig, this);
        menuDao = new MenuDao(menuDaoConfig, this);
        noticeDao = new NoticeDao(noticeDaoConfig, this);
        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);
        timeAxisDao = new TimeAxisDao(timeAxisDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Configure.class, configureDao);
        registerDao(Exam.class, examDao);
        registerDao(ExpLesson.class, expLessonDao);
        registerDao(Grade.class, gradeDao);
        registerDao(GradeRank.class, gradeRankDao);
        registerDao(GradeSum.class, gradeSumDao);
        registerDao(Lesson.class, lessonDao);
        registerDao(Menu.class, menuDao);
        registerDao(Notice.class, noticeDao);
        registerDao(SearchHistory.class, searchHistoryDao);
        registerDao(TimeAxis.class, timeAxisDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        configureDaoConfig.clearIdentityScope();
        examDaoConfig.clearIdentityScope();
        expLessonDaoConfig.clearIdentityScope();
        gradeDaoConfig.clearIdentityScope();
        gradeRankDaoConfig.clearIdentityScope();
        gradeSumDaoConfig.clearIdentityScope();
        lessonDaoConfig.clearIdentityScope();
        menuDaoConfig.clearIdentityScope();
        noticeDaoConfig.clearIdentityScope();
        searchHistoryDaoConfig.clearIdentityScope();
        timeAxisDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public ConfigureDao getConfigureDao() {
        return configureDao;
    }

    public ExamDao getExamDao() {
        return examDao;
    }

    public ExpLessonDao getExpLessonDao() {
        return expLessonDao;
    }

    public GradeDao getGradeDao() {
        return gradeDao;
    }

    public GradeRankDao getGradeRankDao() {
        return gradeRankDao;
    }

    public GradeSumDao getGradeSumDao() {
        return gradeSumDao;
    }

    public LessonDao getLessonDao() {
        return lessonDao;
    }

    public MenuDao getMenuDao() {
        return menuDao;
    }

    public NoticeDao getNoticeDao() {
        return noticeDao;
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

    public TimeAxisDao getTimeAxisDao() {
        return timeAxisDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
