package cn.nicolite.huthelper.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.nicolite.huthelper.model.bean.Exam;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EXAM".
*/
public class ExamDao extends AbstractDao<Exam, Long> {

    public static final String TABLENAME = "EXAM";

    /**
     * Properties of entity Exam.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, String.class, "userId", false, "USER_ID");
        public final static Property KKDepNo = new Property(2, String.class, "KKDepNo", false, "KKDEP_NO");
        public final static Property CourseName = new Property(3, String.class, "CourseName", false, "COURSE_NAME");
        public final static Property Starttime = new Property(4, String.class, "Starttime", false, "STARTTIME");
        public final static Property EndTime = new Property(5, String.class, "EndTime", false, "END_TIME");
        public final static Property Week_Num = new Property(6, String.class, "Week_Num", false, "WEEK__NUM");
        public final static Property Isset = new Property(7, String.class, "isset", false, "ISSET");
        public final static Property RoomName = new Property(8, String.class, "RoomName", false, "ROOM_NAME");
    }


    public ExamDao(DaoConfig config) {
        super(config);
    }
    
    public ExamDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EXAM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" TEXT," + // 1: userId
                "\"KKDEP_NO\" TEXT," + // 2: KKDepNo
                "\"COURSE_NAME\" TEXT," + // 3: CourseName
                "\"STARTTIME\" TEXT," + // 4: Starttime
                "\"END_TIME\" TEXT," + // 5: EndTime
                "\"WEEK__NUM\" TEXT," + // 6: Week_Num
                "\"ISSET\" TEXT," + // 7: isset
                "\"ROOM_NAME\" TEXT);"); // 8: RoomName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EXAM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Exam entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(2, userId);
        }
 
        String KKDepNo = entity.getKKDepNo();
        if (KKDepNo != null) {
            stmt.bindString(3, KKDepNo);
        }
 
        String CourseName = entity.getCourseName();
        if (CourseName != null) {
            stmt.bindString(4, CourseName);
        }
 
        String Starttime = entity.getStarttime();
        if (Starttime != null) {
            stmt.bindString(5, Starttime);
        }
 
        String EndTime = entity.getEndTime();
        if (EndTime != null) {
            stmt.bindString(6, EndTime);
        }
 
        String Week_Num = entity.getWeek_Num();
        if (Week_Num != null) {
            stmt.bindString(7, Week_Num);
        }
 
        String isset = entity.getIsset();
        if (isset != null) {
            stmt.bindString(8, isset);
        }
 
        String RoomName = entity.getRoomName();
        if (RoomName != null) {
            stmt.bindString(9, RoomName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Exam entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(2, userId);
        }
 
        String KKDepNo = entity.getKKDepNo();
        if (KKDepNo != null) {
            stmt.bindString(3, KKDepNo);
        }
 
        String CourseName = entity.getCourseName();
        if (CourseName != null) {
            stmt.bindString(4, CourseName);
        }
 
        String Starttime = entity.getStarttime();
        if (Starttime != null) {
            stmt.bindString(5, Starttime);
        }
 
        String EndTime = entity.getEndTime();
        if (EndTime != null) {
            stmt.bindString(6, EndTime);
        }
 
        String Week_Num = entity.getWeek_Num();
        if (Week_Num != null) {
            stmt.bindString(7, Week_Num);
        }
 
        String isset = entity.getIsset();
        if (isset != null) {
            stmt.bindString(8, isset);
        }
 
        String RoomName = entity.getRoomName();
        if (RoomName != null) {
            stmt.bindString(9, RoomName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Exam readEntity(Cursor cursor, int offset) {
        Exam entity = new Exam( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // KKDepNo
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // CourseName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // Starttime
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // EndTime
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // Week_Num
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // isset
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // RoomName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Exam entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setKKDepNo(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCourseName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setStarttime(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setEndTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setWeek_Num(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setIsset(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setRoomName(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Exam entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Exam entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Exam entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
