package cn.nicolite.huthelper.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.nicolite.huthelper.model.bean.ExpLesson;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EXP_LESSON".
*/
public class ExpLessonDao extends AbstractDao<ExpLesson, Long> {

    public static final String TABLENAME = "EXP_LESSON";

    /**
     * Properties of entity ExpLesson.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, String.class, "userId", false, "USER_ID");
        public final static Property Teacher = new Property(2, String.class, "teacher", false, "TEACHER");
        public final static Property Lesson = new Property(3, String.class, "lesson", false, "LESSON");
        public final static Property Obj = new Property(4, String.class, "obj", false, "OBJ");
        public final static Property Locate = new Property(5, String.class, "locate", false, "LOCATE");
        public final static Property Weeks_no = new Property(6, String.class, "weeks_no", false, "WEEKS_NO");
        public final static Property Week = new Property(7, String.class, "week", false, "WEEK");
        public final static Property Lesson_no = new Property(8, String.class, "lesson_no", false, "LESSON_NO");
        public final static Property Period = new Property(9, String.class, "period", false, "PERIOD");
        public final static Property Real_time = new Property(10, String.class, "real_time", false, "REAL_TIME");
    }


    public ExpLessonDao(DaoConfig config) {
        super(config);
    }
    
    public ExpLessonDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EXP_LESSON\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"USER_ID\" TEXT," + // 1: userId
                "\"TEACHER\" TEXT," + // 2: teacher
                "\"LESSON\" TEXT," + // 3: lesson
                "\"OBJ\" TEXT," + // 4: obj
                "\"LOCATE\" TEXT," + // 5: locate
                "\"WEEKS_NO\" TEXT," + // 6: weeks_no
                "\"WEEK\" TEXT," + // 7: week
                "\"LESSON_NO\" TEXT," + // 8: lesson_no
                "\"PERIOD\" TEXT," + // 9: period
                "\"REAL_TIME\" TEXT);"); // 10: real_time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EXP_LESSON\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ExpLesson entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(2, userId);
        }
 
        String teacher = entity.getTeacher();
        if (teacher != null) {
            stmt.bindString(3, teacher);
        }
 
        String lesson = entity.getLesson();
        if (lesson != null) {
            stmt.bindString(4, lesson);
        }
 
        String obj = entity.getObj();
        if (obj != null) {
            stmt.bindString(5, obj);
        }
 
        String locate = entity.getLocate();
        if (locate != null) {
            stmt.bindString(6, locate);
        }
 
        String weeks_no = entity.getWeeks_no();
        if (weeks_no != null) {
            stmt.bindString(7, weeks_no);
        }
 
        String week = entity.getWeek();
        if (week != null) {
            stmt.bindString(8, week);
        }
 
        String lesson_no = entity.getLesson_no();
        if (lesson_no != null) {
            stmt.bindString(9, lesson_no);
        }
 
        String period = entity.getPeriod();
        if (period != null) {
            stmt.bindString(10, period);
        }
 
        String real_time = entity.getReal_time();
        if (real_time != null) {
            stmt.bindString(11, real_time);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ExpLesson entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(2, userId);
        }
 
        String teacher = entity.getTeacher();
        if (teacher != null) {
            stmt.bindString(3, teacher);
        }
 
        String lesson = entity.getLesson();
        if (lesson != null) {
            stmt.bindString(4, lesson);
        }
 
        String obj = entity.getObj();
        if (obj != null) {
            stmt.bindString(5, obj);
        }
 
        String locate = entity.getLocate();
        if (locate != null) {
            stmt.bindString(6, locate);
        }
 
        String weeks_no = entity.getWeeks_no();
        if (weeks_no != null) {
            stmt.bindString(7, weeks_no);
        }
 
        String week = entity.getWeek();
        if (week != null) {
            stmt.bindString(8, week);
        }
 
        String lesson_no = entity.getLesson_no();
        if (lesson_no != null) {
            stmt.bindString(9, lesson_no);
        }
 
        String period = entity.getPeriod();
        if (period != null) {
            stmt.bindString(10, period);
        }
 
        String real_time = entity.getReal_time();
        if (real_time != null) {
            stmt.bindString(11, real_time);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ExpLesson readEntity(Cursor cursor, int offset) {
        ExpLesson entity = new ExpLesson( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // teacher
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // lesson
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // obj
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // locate
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // weeks_no
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // week
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // lesson_no
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // period
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // real_time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ExpLesson entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTeacher(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLesson(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setObj(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setLocate(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setWeeks_no(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setWeek(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setLesson_no(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setPeriod(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setReal_time(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ExpLesson entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ExpLesson entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ExpLesson entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
