package cn.nicolite.huthelper.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.nicolite.huthelper.model.bean.Grade;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GRADE".
*/
public class GradeDao extends AbstractDao<Grade, Long> {

    public static final String TABLENAME = "GRADE";

    /**
     * Properties of entity Grade.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, String.class, "userId", false, "USER_ID");
        public final static Property Xh = new Property(2, String.class, "xh", false, "XH");
        public final static Property Xn = new Property(3, String.class, "xn", false, "XN");
        public final static Property Xq = new Property(4, String.class, "xq", false, "XQ");
        public final static Property Kcmc = new Property(5, String.class, "kcmc", false, "KCMC");
        public final static Property Xf = new Property(6, String.class, "xf", false, "XF");
        public final static Property Cj = new Property(7, String.class, "cj", false, "CJ");
        public final static Property Zscj = new Property(8, String.class, "zscj", false, "ZSCJ");
        public final static Property Bkcj = new Property(9, String.class, "bkcj", false, "BKCJ");
        public final static Property Jd = new Property(10, String.class, "jd", false, "JD");
        public final static Property Cxbj = new Property(11, String.class, "cxbj", false, "CXBJ");
        public final static Property Kcxz = new Property(12, String.class, "kcxz", false, "KCXZ");
        public final static Property Bj = new Property(13, String.class, "bj", false, "BJ");
    }


    public GradeDao(DaoConfig config) {
        super(config);
    }
    
    public GradeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GRADE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"USER_ID\" TEXT," + // 1: userId
                "\"XH\" TEXT," + // 2: xh
                "\"XN\" TEXT," + // 3: xn
                "\"XQ\" TEXT," + // 4: xq
                "\"KCMC\" TEXT," + // 5: kcmc
                "\"XF\" TEXT," + // 6: xf
                "\"CJ\" TEXT," + // 7: cj
                "\"ZSCJ\" TEXT," + // 8: zscj
                "\"BKCJ\" TEXT," + // 9: bkcj
                "\"JD\" TEXT," + // 10: jd
                "\"CXBJ\" TEXT," + // 11: cxbj
                "\"KCXZ\" TEXT," + // 12: kcxz
                "\"BJ\" TEXT);"); // 13: bj
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GRADE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Grade entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(2, userId);
        }
 
        String xh = entity.getXh();
        if (xh != null) {
            stmt.bindString(3, xh);
        }
 
        String xn = entity.getXn();
        if (xn != null) {
            stmt.bindString(4, xn);
        }
 
        String xq = entity.getXq();
        if (xq != null) {
            stmt.bindString(5, xq);
        }
 
        String kcmc = entity.getKcmc();
        if (kcmc != null) {
            stmt.bindString(6, kcmc);
        }
 
        String xf = entity.getXf();
        if (xf != null) {
            stmt.bindString(7, xf);
        }
 
        String cj = entity.getCj();
        if (cj != null) {
            stmt.bindString(8, cj);
        }
 
        String zscj = entity.getZscj();
        if (zscj != null) {
            stmt.bindString(9, zscj);
        }
 
        String bkcj = entity.getBkcj();
        if (bkcj != null) {
            stmt.bindString(10, bkcj);
        }
 
        String jd = entity.getJd();
        if (jd != null) {
            stmt.bindString(11, jd);
        }
 
        String cxbj = entity.getCxbj();
        if (cxbj != null) {
            stmt.bindString(12, cxbj);
        }
 
        String kcxz = entity.getKcxz();
        if (kcxz != null) {
            stmt.bindString(13, kcxz);
        }
 
        String bj = entity.getBj();
        if (bj != null) {
            stmt.bindString(14, bj);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Grade entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(2, userId);
        }
 
        String xh = entity.getXh();
        if (xh != null) {
            stmt.bindString(3, xh);
        }
 
        String xn = entity.getXn();
        if (xn != null) {
            stmt.bindString(4, xn);
        }
 
        String xq = entity.getXq();
        if (xq != null) {
            stmt.bindString(5, xq);
        }
 
        String kcmc = entity.getKcmc();
        if (kcmc != null) {
            stmt.bindString(6, kcmc);
        }
 
        String xf = entity.getXf();
        if (xf != null) {
            stmt.bindString(7, xf);
        }
 
        String cj = entity.getCj();
        if (cj != null) {
            stmt.bindString(8, cj);
        }
 
        String zscj = entity.getZscj();
        if (zscj != null) {
            stmt.bindString(9, zscj);
        }
 
        String bkcj = entity.getBkcj();
        if (bkcj != null) {
            stmt.bindString(10, bkcj);
        }
 
        String jd = entity.getJd();
        if (jd != null) {
            stmt.bindString(11, jd);
        }
 
        String cxbj = entity.getCxbj();
        if (cxbj != null) {
            stmt.bindString(12, cxbj);
        }
 
        String kcxz = entity.getKcxz();
        if (kcxz != null) {
            stmt.bindString(13, kcxz);
        }
 
        String bj = entity.getBj();
        if (bj != null) {
            stmt.bindString(14, bj);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Grade readEntity(Cursor cursor, int offset) {
        Grade entity = new Grade( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // xh
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // xn
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // xq
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // kcmc
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // xf
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // cj
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // zscj
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // bkcj
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // jd
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // cxbj
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // kcxz
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13) // bj
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Grade entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setXh(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setXn(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setXq(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setKcmc(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setXf(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCj(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setZscj(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setBkcj(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setJd(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setCxbj(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setKcxz(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setBj(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Grade entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Grade entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Grade entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
